Refactor contracts and compile preinstalled contracts from source
OffchainLabs/arb-os pull request #272
Opened 2020-12-22 12:51 UTC by edfelten

* Refactor / rename the contracts and interfaces used by ArbOS, to rationalize naming and directory structure.
* Compile preinstalled contracts (ArbInfo and the ERC20/ERC721 templates) from Solidity source, rather than hardcoding their byte code into the Rust source code.
* Update ERC20/721 template contracts for compatibility with the latest version of OpenZeppelin.

2020-12-22 21:58 UTC, hkalodner requested changes
The open zeppelin repo should be checked out to a particular release tag rather than the current head. Other than that and the one small comment, this looks good

2020-12-22 22:43 UTC, edfelten commented on src/evm/abi.rs
> +    let abi = AbiForContract::new_from_file("contracts/arbos/build/contracts/ArbSys.json").unwrap();
Fixed

2020-12-22 22:43 UTC, edfelten commented
> The open zeppelin repo should be checked out to a particular release tag rather than the current head. Other than that and the one small comment, this looks good

Pinned it to version 3.3.0.

2020-12-23 01:57 UTC, hkalodner submitted a review, later dismissed
LGTM

2020-12-23 02:25 UTC, edfelten commented
Merging this as Harry and I are both OK with the latest changes.

2020-12-23 02:25 UTC, merged

2020-12-23 02:25 UTC, hkalodner approved these changes
LGTM