New chain params system
OffchainLabs/arb-os pull request #500
Opened 2021-05-29 14:26 UTC by edfelten

2021-07-28 16:26 UTC, PlasmaPower requested changes

2021-07-28 16:26 UTC, PlasmaPower commented on src/main.rs
> +                    panic!("{}", e);
If you're going to panic with the error, you might as well call unwrap on the result.

2021-07-29 15:35 UTC, PlasmaPower commented on arb_os/arbowner.mini
> +impure func arbowner_setFairGasPriceSender(_topFrame: EvmCallFrame, calldata: ByteArray) { // (address)
This was just moved around in this PR, but this comment is wrong. The params are `(address, bool)`.

2021-07-29 15:47 UTC, edfelten commented on arb_os/arbowner.mini
> +            bytearray_set256(bytearray_new(0), 0, 64),
The ultimate fix for this is the antigen tool, which is in our pipeline.  So I prefer to leave this as is for now.

2021-07-29 16:20 UTC, edfelten commented on arb_os/chainParameters.mini
> +    globalChainParameters = globalChainParameters with { [which] = value };
Changed this to validate that the param already exists.  Added a new chainParams_create which sets the value regardless of whether it existed before.

2021-07-29 16:21 UTC, edfelten commented on arb_os/chainParameters.mini
> +            0
Agree. Changed it.

2021-08-04 22:06 UTC, PlasmaPower commented on arb_os/chainParameters.mini
> +    globalChainParameters = globalChainParameters with { [which] = value };
This fix and the one for chainParams_gotParamsMessage don't seem to have been pushed up yet

2021-09-07 17:46 UTC, RachelFranks commented
This has been merged

2021-09-07 17:46 UTC, closed without merging